### ISSUE TITLE
Some Captcha Error

### ISSUE THREAD

**Issue by Amneziaaa** [Pr0t0ns/Pr0t0n-X-ADylan-Token-Creator-Joiner#1]
An Error Occured While Creating account or joining Server
Possible Invalid Captcha Response!
Response: {"captcha_key": ["invalid-response"], "captcha_sitekey": "4c672d35-0701-42b2-88c3-78380b0db560", "captcha_service": "hcaptcha"}
Exception in thread Thread-3 (join_server):
Traceback (most recent call last):
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rk_cr\Desktop\Pr0t0n-X-ADylan-Token-Creator-Joiner-main\joiner.py", line 143, in join_server
    data = session.post(url, headers=headers, json=payload)
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 321, in prepare
    self.prepare_body(data, files, json)
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 473, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\rk_cr\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable

**Comment by Pr0t0ns** [comment]
new release should fix this error
