### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Altify-Development** [Pr0t0ns/Pr0t0n-X-ADylan-Token-Creator-Joiner#5]

**Comment by Altify-Development** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zekel\Documents\Pr0t0n-X-ADylan-Token-Creator-Joiner-main\joiner.py", line 136, in join_server
    fingerprint = get_fingerprint(proxy)
  File "C:\Users\zekel\Documents\Pr0t0n-X-ADylan-Token-Creator-Joiner-main\joiner.py", line 107, in get_fingerprint
    return join_server()
  File "C:\Users\zekel\Documents\Pr0t0n-X-ADylan-Token-Creator-Joiner-main\joiner.py", line 137, in join_server
    captcha = solve_captcha(proxy)
  File "C:\Users\zekel\Documents\Pr0t0n-X-ADylan-Token-Creator-Joiner-main\joiner.py", line 80, in solve_captcha
    captchakey = httpx.post("http://ezcaptcha.us:8080/solvecaptcha", json={
  File "C:\Python310\lib\site-packages\httpx\_api.py", line 304, in post
    return request(
  File "C:\Python310\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "C:\Python310\lib\site-packages\httpx\_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Python310\lib\site-packages\httpx\_client.py", line 902, in send
    response = self._send_handling_auth(
  File "C:\Python310\lib\site-packages\httpx\_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Python310\lib\site-packages\httpx\_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Python310\lib\site-packages\httpx\_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Python310\lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "C:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python310\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.
